CREATE TABLE notas (
    id SERIAL PRIMARY KEY,
    titulo VARCHAR(255) NOT NULL,
    nota TEXT NOT NULL,
    data_criacao TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ultima_atualizacao TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
